/*
 * This Java source file was auto generated by running 'lombok buildInit --type java-library'
 * by 'Coupang' at '14. 7. 3 오후 1:57' with Gradle 1.12
 *
 * @author Coupang, @date 14. 7. 3 오후 1:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
