import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'lombok init --type java-library'
 * by 'Coupang' at '14. 7. 3 오후 1:57' with Gradle 1.12
 *
 * @author Coupang, @date 14. 7. 3 오후 1:57
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
